version: "3.2"
services:
  # # https://hub.docker.com/_/node/
  server:
    build:
      context: ./server
    environment:
      - MONGO_HOST=db
      - REDIS_HOST=mem
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - db
      - mem
      - proxy
    # tty: false
    
    labels:
    - "videoaulas server in production mode"
    container_name: server
    