version: "3.2"
services:
  # https://hub.docker.com/_/mongo/
  db:
    image: mongo:3.4.4
    command: --auth
    volumes:
      - ./server/config/mongo/data/db:/data/db
    ports:
      - 27017:27017
    # tty: true
    container_name: db

  # https://hub.docker.com/_/redis/
  mem:
    image: redis:3.2.8-alpine
    ports:
     - 6379:6379
    # tty: true
    container_name: mem

  # https://hub.docker.com/_/nginx/
  proxy:
    build:
      context: ./web

    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/config/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./web/config/proxy/default:/etc/nginx/sites-enabled/default
    # links:
    #   - server
    container_name: proxy

    # COPY config/proxy/nginx.conf /etc/nginx/nginx.conf
    # COPY config/proxy/default /etc/nginx/sites-enabled/default
    
  server:
    build:
      context: ./server
    environment:
      - MONGO_HOST=db
      - REDIS_HOST=mem
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - db
      - mem
      - proxy
    # tty: false
    
    labels:
    - "videoaulas server in production mode"
    container_name: server