version: "3.2"
services:
  # https://hub.docker.com/_/nginx/
  proxy:
    build:
      context: ./web

    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/config/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./web/config/proxy/default:/etc/nginx/sites-enabled/default
    # links:
    #   - server
    container_name: proxy

    # COPY config/proxy/nginx.conf /etc/nginx/nginx.conf
    # COPY config/proxy/default /etc/nginx/sites-enabled/default