version: "3.2"
services:
  # https://hub.docker.com/_/mongo/
  db:
    image: mongo:3.4.4
    command: --auth
    volumes:
      - ./server/config/mongo/data/db:/data/db
    ports:
      - 27017:27017
    # tty: true
    container_name: db

  # https://hub.docker.com/_/redis/
  mem:
    image: redis:3.2.8-alpine
    ports:
     - 6379:6379
    # tty: true
    container_name: mem
    