version: "3.2"
services:
  # https://hub.docker.com/_/mongo/
  db:
    image: mongo:3.4.4
    command: --auth
    volumes:
      - ./server/config/mongo/data/db:/data/db
    ports:
      - 27017:27017
    # tty: true
    container_name: db

  # https://hub.docker.com/_/redis/
  mem:
    image: redis:3.2.8-alpine
    ports:
     - 6379:6379
    # tty: true
    container_name: mem

  # web:
  #   image: node:8.4.0-alpine
  #   working_dir: /web
  #   environment:
  #     - MONGO_HOST=db
  #     - NODE_ENV=development
  #   ports:
  #     - 3001:3001
  #     - 3000:3000
  #   # links:
  #   #   - db
  #   #   - mem
  #   # tty: false
  #   labels:
  #   - "videoaulas web in development mode"
  #   container_name: web
  #   # read_only: true
  #   volumes: 
  #     - ./web/:/web

  #   entrypoint: sh -c "export NODE_ENV=development && export PORT=3001 && npm run start"

  # # https://hub.docker.com/_/node/
  # server:
  #   image: node:8.4.0-alpine
  #   working_dir: /server    
  #   environment:
  #     - MONGO_HOST=db
  #     - NODE_ENV=development
  #   # ports:
  #   #   - 3001:3001    
  #   #   - 3000:3000
  #   links:
  #     - db
  #     - mem
  #     - web
  #   # tty: false
  #   labels:
  #   - "videoaulas server in dev mode"
  #   container_name: server
  #   # read_only: true
  #   volumes: 
  #     - ./server:/server
  #   entrypoint: sh -c "export NODE_ENV=development && export PORT=3000 && npm run dev"

    # volumes:
      # - ./dist:/www/dist
      # - ./dist-server:/www/dist-server
      # - ./public:/www/public
      # - ./package.json:/www/package.json
      # - ./node_modules:/www/node_modules
      # - ./bin:/www/bin
      # - ./config:/www/config