version: "3.2"
services:
  # https://hub.docker.com/_/node/
  web:
    build: .
    environment:
      - MONGO_HOST=db
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - db
      - mem
    # tty: false
    labels:
    - "videoaulas app in production mode"
    container_name: app
    # read_only: true
    volumes: 
      - ./dist:/www/dist:ro
      - ./dist-server:/www/dist-server:ro
      - ./public:/www/public:ro
      - ./package.json:/www/package.json:ro
      - ./bin:/www/bin:ro
      - ./config:/www/config
    entrypoint: sh -c "npm install && npm run deploy-prod:light && npm start"
    
  # https://hub.docker.com/_/nginx/
  proxy:
    image: nginx:1.13.0-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    # read_only: false
    volumes:
      - ./config/deploy/ssl:/var/ssl
      - ./:/var/www
      - ./config/deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./config/deploy/default:/etc/nginx/sites-enabled/default
    links:
      - app
    # tty: true
    container_name: web